# Generated by Django 5.1.5 on 2025-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_painting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
