# Generated by Django 5.1.5 on 2025-02-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_alter_painting_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
